### PR TITLE
Upgrade to 1.19.3.1

### PR DESCRIPTION
**Pull request by kshitijmjoshi**
* Upgrade OpenResty to 1.19.3.1 (#166)
 * Added some documentation to nginx.conf file
 * Added gitignore

### CODE REVIEW

**Comment by neomantra** [comment]
Thank you for this commit!  I'm testing it out and will push to CI soon. 

I'm concerned with changing the `worker_processes` default.  I just checked and the `nginx` image keeps it at `1`.  But we do handle some things differently as OpenResty is more of an application server.     I appreciate wanting to be able to control this.  I'm researching this more.

**Comment by kshitijmjoshi** [comment]
> worker_processes

We can comment it out and open a new MR for it so it won't block the 1.19 release.

**Comment by neomantra** [comment]
I commented `worker_processes` out as the default is `1` anyway, and I'd prefer users set their own to an override.

That's pushed and on CI/CD.  Once that is successful, I'll tag it and push.

**Comment by neomantra** [comment]
This is building -- just Travis is really slow today.

**Comment by fabiant7t** [comment]
Just found out that `openresty/openresty:1.19.3.1-alpine-apk` and `openresty/openresty:1.19.3.1-alpine-amd64` differ in terms of shipped modules. E.g.. `alpine-apk` does not ship with the `http_slice_module` while `alpine-amd64` does. Is this intended? Shouldn't they be interchangeable?
 
```
# openresty/openresty:1.19.3.1-alpine-apk
/ # nginx -V
nginx version: openresty/1.19.3.1
built by gcc 9.3.0 (Alpine 9.3.0) 
built with OpenSSL 1.1.1h  22 Sep 2020
TLS SNI support enabled
configure arguments: --prefix=/usr/local/openresty/nginx --with-cc-opt='-O2 -DNGX_LUA_ABORT_AT_PANIC -I/usr/local/openresty/zlib/include -I/usr/local/openresty/pcre/include -I/usr/local/openresty/openssl111/include' --add-module=../ngx_devel_kit-0.3.1 --add-module=../echo-nginx-module-0.62 --add-module=../xss-nginx-module-0.06 --add-module=../ngx_coolkit-0.2 --add-module=../set-misc-nginx-module-0.32 --add-module=../form-input-nginx-module-0.12 --add-module=../encrypted-session-nginx-module-0.08 --add-module=../srcache-nginx-module-0.32 --add-module=../ngx_lua-0.10.19 --add-module=../ngx_lua_upstream-0.07 --add-module=../headers-more-nginx-module-0.33 --add-module=../array-var-nginx-module-0.05 --add-module=../memc-nginx-module-0.19 --add-module=../redis2-nginx-module-0.15 --add-module=../redis-nginx-module-0.3.7 --add-module=../ngx_stream_lua-0.0.9 --with-ld-opt='-Wl,-rpath,/usr/local/openresty/luajit/lib -L/usr/local/openresty/zlib/lib -L/usr/local/openresty/pcre/lib -L/usr/local/openresty/openssl111/lib -Wl,-rpath,/usr/local/openresty/zlib/lib:/usr/local/openresty/pcre/lib:/usr/local/openresty/openssl111/lib' --with-cc='ccache gcc -fdiagnostics-color=always -g3' --with-pcre-jit --with-stream --with-stream_ssl_module --with-stream_ssl_preread_module --with-http_v2_module --without-mail_pop3_module --without-mail_imap_module --without-mail_smtp_module --with-http_stub_status_module --with-http_realip_module --with-http_addition_module --with-http_auth_request_module --with-http_secure_link_module --with-http_random_index_module --with-http_gzip_static_module --with-http_sub_module --with-http_dav_module --with-http_flv_module --with-http_mp4_module --with-http_gunzip_module --with-threads --with-compat --with-stream --with-http_ssl_module
```

```
# openresty/openresty:1.19.3.1-alpine-amd64
/ # openresty -V
nginx version: openresty/1.19.3.1
built by gcc 9.3.0 (Alpine 9.3.0) 
built with OpenSSL 1.1.1g  21 Apr 2020
TLS SNI support enabled
configure arguments: --prefix=/usr/local/openresty/nginx --with-cc-opt='-O2 -DNGX_LUA_ABORT_AT_PANIC -I/usr/local/openresty/pcre/include -I/usr/local/openresty/openssl/include' --add-module=../ngx_devel_kit-0.3.1 --add-module=../echo-nginx-module-0.62 --add-module=../xss-nginx-module-0.06 --add-module=../ngx_coolkit-0.2 --add-module=../set-misc-nginx-module-0.32 --add-module=../form-input-nginx-module-0.12 --add-module=../encrypted-session-nginx-module-0.08 --add-module=../srcache-nginx-module-0.32 --add-module=../ngx_lua-0.10.19 --add-module=../ngx_lua_upstream-0.07 --add-module=../headers-more-nginx-module-0.33 --add-module=../array-var-nginx-module-0.05 --add-module=../memc-nginx-module-0.19 --add-module=../redis2-nginx-module-0.15 --add-module=../redis-nginx-module-0.3.7 --add-module=../rds-json-nginx-module-0.15 --add-module=../rds-csv-nginx-module-0.09 --add-module=../ngx_stream_lua-0.0.9 --with-ld-opt='-Wl,-rpath,/usr/local/openresty/luajit/lib -L/usr/local/openresty/pcre/lib -L/usr/local/openresty/openssl/lib -Wl,-rpath,/usr/local/openresty/pcre/lib:/usr/local/openresty/openssl/lib' --with-pcre --with-compat --with-file-aio --with-http_addition_module --with-http_auth_request_module --with-http_dav_module --with-http_flv_module --with-http_geoip_module=dynamic --with-http_gunzip_module --with-http_gzip_static_module --with-http_image_filter_module=dynamic --with-http_mp4_module --with-http_random_index_module --with-http_realip_module --with-http_secure_link_module --with-http_slice_module --with-http_ssl_module --with-http_stub_status_module --with-http_sub_module --with-http_v2_module --with-http_xslt_module=dynamic --with-ipv6 --with-mail --with-mail_ssl_module --with-md5-asm --with-pcre-jit --with-sha1-asm --with-stream --with-stream_ssl_module --with-threads --with-stream --with-stream_ssl_preread_module
```

**Comment by neomantra** [comment]
@fabiant7t Thanks helping verify the release!   The `alpine-apk` is built from upstream OpenResty packages, whereas the `alpine` packages are built from source (BFS).  The BFS flavors have different build options from the upstream flavors; there's an [issue to harmonize that better](#109).  We try to keep the same as upstream modules and add sensible extras that people have requested over the years.  So it makes sense that there might be an extra module.

It looks like upstream might have one `arm64` [pre-built package](http://openresty.org/en/linux-packages.html), but we haven't incorporated multi-architecture built-from-upstream Docker tooling.

**Pull request closed without merging**
