### PR TITLE
Adding build args as per issue #79 on official repo

### PR DESCRIPTION
**Pull request by RVN-BR**
As per https://github.com/openresty/docker-openresty/issues/79 this commit adds 3 new build variables to allow for a docker image that can be customized with additional modules.

Per our requirement we needed to download a module from a git repo (git clone - which required installing a package), then add it to the ./configure (already supported by  RESTY_CONFIG_OPTIONS_MORE argument), and for the sakes of cleanliness perform some cleanup after the configure as well as removing the installed package.

This is accomplished with the following:
RESTY_ADD_PACKAGE_BUILDDEPS - packages added to this argument are added for the build process and then removed after the build automatically. example: "git" or "git wget"
RESTY_SCRIPT_BEFORE_CONFIG - any command here will be executed before ./configure (it executes inside the /tmp directory where other packages are also downloaded).  example: "git clone git://github.com/author/module-name"
RESTY_SCRIPT_AFTER_MAKE - any command here will execute after make install for openresty.  My use is primarily for cleanup, although there may be other needs? example: "rm -rf module-name" (to remove the directory cloned)

### CODE REVIEW

**Comment by RVN-BR** [comment]
Waiting for this one to be accepted or rejected based on new names.

**Comment by neomantra** [comment]
Yes that looks good... I guess it makes sense (while we are doing this) to have a `RESTY_ADD_PACKAGE_RUNDEPS` for run-time dependencies.

Are you comfortable making the changes to the `xenial` and `bionic` images?  If not I can.  

Can you also add yourself to AUTHORS (if you want), and update the README with these defaults and a blurb about the functionality in the "spin your own image" section.

**Comment by RVN-BR** [comment]
I thought about RUNDEPS but decided it was easy enough to add an apk add as a pre_config command, but I'm fine to add it... Thought it could polute the image too much with too many options, but if you are ok with it I guess it makes it a bit friendlier for some users.

I'll get to this tomorrow and add proposed changes to the doc.

Rgds

**Comment by RVN-BR** [comment]
@neomantra just making sure you dont miss these updates when you have a chance.  I explained the changes in issue #79

**Comment by neomantra** [comment]
Sorry it took me a while to get back to this.   I have a minor fixes ready which address:
 * removed `resty_luarocks_version` label
 * added ubuntu build-dep package removal

But one thing I wanted to verify:   shouldn't the bash tests be using `-n` instead of `-z`,   If `-n` then the environment variable is no-zero so the eval should go?  right?   I can put that on my tree if you confirm and then i'll squash and merge this.

**Comment by RVN-BR** [comment]
Hi @neomantra I doble checked now, and you are in fact correct... amidst doing the changes to the variable names I missed one in my local version and a -z worked opposite to what it should have...

Go ahead and change those if you can! that makes more sense... thanks!!

**Comment by neomantra** [comment]
I just added the fixes,  squashed, and merged.  Thanks for the help.

Funny thing, I saw the branch name had `NeoAssist` and thought it was because you were "assisting" "neomantra" in this pull request... then I see it's actually the organization you are affiliated with. ;)

**Pull request closed without merging**
