### PR TITLE
Stop with SIGQUIT so that "docker stop" is actually a graceful stop

### PR DESCRIPTION
**Pull request by josephcsible**

### CODE REVIEW

**Comment by neomantra** [comment]
Thanks for contributing.  It looks like the official Nginx Docker images use `STOPSIGNAL SIGTERM`.  This is really the Docker default anyway, and from reading some of their issue comments they put it in the Dockerfile to be explicit.  

It also looks like there is an outstanding Nginx bug with SIGQUIT: https://trac.nginx.org/nginx/ticket/753

Can you go into more detail why you think this is needed?   Maybe something else is going on?

**Comment by josephcsible** [comment]
SIGTERM makes the server stop immediately when it's used, instead of waiting for connections to close. I think the latter is much more useful for "docker stop". In my mind, the former behavior isn't very useful, as you can get that with "docker kill".

As for the bug, I don't expect that many people will be listening on socket files in a Docker environment, it's easy to work around, and people already have to deal with its effect if the server ever stops unexpectedly.

**Comment by neomantra** [comment]
I've checked some other nginx distributions (official Docker, Kong) and they explicitly use the default `STOPSIGNAL SIGTERM` .  For lack of confusion, for now I want keep parity with them, particularly because this can be easily modified at the control plane level.

I think what you raise is *very* important.  Operators should know about this.   I will make a documentation bug about this.

Other things I'm concerned with:
  * Linux manpage says `SIGQUIT` dumps core.  Does it do that in this case?
  * [the unix socket bug](https://trac.nginx.org/nginx/ticket/753), maybe less important in a container context.

**Comment by josephcsible** [comment]
> Linux manpage says SIGQUIT dumps core. Does it do that in this case?

No. The presence of Nginx's graceful shutdown handler on this signal overrides this.

**Comment by neomantra** [comment]
In a showerthought I realized you are right and `SIGQUIT` is a better default, especially since these images are for application servers (versus proxies).

Can you add a documentation paragraph about it?  Mentioning the differences, and linking the unix socket bug?

Also please add this to the `bionic` flavor that was just pushed.

If you are interested in being listed in the AUTHORS page, add yourself.  

Thanks!

**Comment by neomantra** [comment]
I didn't realize you had updated your pull request.   I updated some docs and applied it to some other Dockerfiles.  That's pushed and I'm tagging 1.13.6.2-2.  Thanks again for the contribution.

**Pull request closed without merging**
