### PR TITLE
Add debian buster image variant

### PR DESCRIPTION
**Pull request by JoelLinn**
Adds buster image variant based on stretch Dockerfiles.
Note that changes to `.travis.yml` are untested

### CODE REVIEW

**Comment by neomantra** [comment]
I didn't realize upstream added Buster packages, great.  Thanks for putting this together and being comprehensive with it.   I'll review and get it up this weekend.   

If you want to be in the `AUTHORS` file, let me know what email address to use.

**Comment by JoelLinn** [comment]
You're welcome!
My mail is jl@conductive.de

**Comment by JoelLinn** [comment]
Did you find the time to review my changes?
I can amend my commit if you have any concerns.

**Comment by neomantra** [comment]
Sorry, I didn't get to it until this past weekend.  The tagged build just finished, so this is available in image `1.15.8.2-4`.  Thanks again!

**Pull request closed without merging**
