### PR TITLE
chore: upgrade alpine to 3.18

### PR DESCRIPTION
**Pull request by josegonzalez**

### CODE REVIEW

**Comment by neomantra** [comment]
Thanks, but upstream doesn't have it yet:
https://openresty.org/package/alpine/

**Comment by josegonzalez** [comment]
😬 sorry about that! How can I help add newer alpine to the release for upstream 🤔

**Comment by leytonreed** [comment]
An upstream package for Alpine now seems to be available:
https://openresty.org/package/alpine/v3.18/main/x86_64/openresty-1.21.4.3-r0.apk

Can an upgrade to 3.18 be reconsidered?

**Comment by neomantra** [comment]
Thanks for bringing this to my attention.  I just pushed a commit for that and will tag once CI/CD is done.

**Comment by neomantra** [comment]
Closed this with this commit: https://github.com/openresty/docker-openresty/commit/6abc5e835b7edc6f246309c706b2cb0a6a43a355

**Pull request closed without merging**
