### PR TITLE
Update PATH to include custom binaries in containers

### PR DESCRIPTION
**Pull request by onnimonni**
This is just for the convenience when people might do extra installations on top of this image.

### CODE REVIEW

**Comment by neomantra** [comment]
Thanks for this PR.  I was originally hesitant on first read, but I see that Docker is OK with this in [Dockerfile Best Practices](https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/)

I would prefer it to be in all the Dockerfiles (except `alpine` maybe) so that it is consistent.  I can do that soon or you can update the PR.

**Comment by onnimonni** [comment]
I think people can override this for `alpine` as well so it doesn't hurt to be included over there too?

I'll add this to other images soon.

**Comment by onnimonni** [comment]
@neomantra I think it's good now :)!

**Comment by neomantra** [comment]
Squashed it into one changeset.  Thanks for contributing!

**Pull request merged**
