### PR TITLE
Add debian stretch image

### PR DESCRIPTION
**Pull request by onnimonni**
Add new version of debian.

This cleans up the build dependencies like #37 does.

### CODE REVIEW

**Comment by agentzh** [comment]
@onnimonni Any reason not to use the new official OpenResty debian stretch packages directly?

https://openresty.org/en/linux-packages.html

**Comment by onnimonni** [comment]
Just that I'm ignorant and didn't know that they exist :)! That's awesome!

**Comment by onnimonni** [comment]
And I still use these images as reference since I need to build openresty with ngx_pagespeed module. For example I don't know how to add dynamic module later on for the apt installed packages.

**Comment by agentzh** [comment]
@onnimonni Official OpenResty docker images should not include 3rd-party NGINX modules that are not maintained by the OpenResty team. For one thing, I never like `ngx_pagespeed` from the technical point of view. It represents the wrong way of solving problems in the NGINX world IMHO.

**Comment by onnimonni** [comment]
Ofc they should not but this it is still useful for us and these Dockerfiles are really easy to expand to include any 3rd-party modules when needed.

**Comment by agentzh** [comment]
@onnimonni But it's also making our lives much harder to synchronize all our build options and patches.

**Comment by agentzh** [comment]
@onnimonni Why don't you simply extend and customize the deb packaging scripts instead? See

https://github.com/happyaron/openresty-packaging

**Comment by agentzh** [comment]
@onnimonni Sorry, I pasted the wrong repo link above. Just fixed. It should be under `openresty/`.

**Comment by neomantra** [comment]
Closing this since #44 was merged.   As #44 is built from Debian packages, the build dependencies are excluded.  The `openresty/stretch` should be on Docker Hub in a few hours.

**Pull request closed without merging**
