### PR TITLE
Vts sts

### PR DESCRIPTION
**Pull request by marrotte**

### CODE REVIEW

**Comment by agentzh** [comment]
We shouldn't include 3rd-party modules that are not supported by the OpenResty team.

**Comment by neomantra** [comment]
Thanks for your pull request.  I agree with @agentzh that we shouldn't include modules that aren't supported by the OpenResty team.  But I do think we should have clear instructions for people who want to add modules in another image layer. #33

Is using different Nginx versions like this advised?  If not, I don't want to include it. I thought much care was made to QA OpenResty against an Nginx version.  If it is OK, then I'd prefer a bit more general implementation (defaulting to none but allowing to set an ARG) and have it applied to all the Dockerfiles. 

What needed `apt-utils`?

**Comment by marrotte** [comment]
This PR was unintentional and meant to PR my fork.  Sorry about that.

**Comment by neomantra** [comment]
Ok closing then.  If good, general ideas come out of this, let us know.

**Pull request closed without merging**
